[tool.briefcase]
project_name = "Quran Radio"
bundle = "com.example.quranradio"
version = "1.0.0"
url = "https://example.com"
author = "MD Bahar"
author_email = "youremail@example.com"
license = "MIT"

[tool.briefcase.app.quranradio]
formal_name = "Quran Radio"
description = "تطبيق لتشغيل إذاعة القرآن الكريم مع تموج صوتي ديناميكي"
sources = ["app.py"]
requires = ["flask"]

[tool.briefcase.app.quranradio.android]
requires = []
