[tool.briefcase]
project_name = "Quran Radio"
bundle = "com.example.quranradio"
version = "1.0.0"
url = "https://example.com"
author = "MD Bahar"
author_email = "youremail@example.com"
license = { text = "MIT" }

[tool.briefcase.app.app]          # ← بدل "quranradio" خلتها "app" لأنها اسم الملف
formal_name = "Quran Radio"
description = "تطبيق لتشغيل إذاعة القرآن الكريم مع تموج صوتي ديناميكي"
sources = ["app.py"]              # ← ملف مباشر مش مجلد
requires = ["flask"]

[tool.briefcase.app.app.android]
requires = []
