name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install briefcase

      - name: Build APK with Briefcase
        run: |
          briefcase create android
          briefcase build android
          briefcase package android

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: QuranRadio-APK
          path: android/outputs/**/*.apk
